# Generated by Django 3.0.7 on 2020-11-19 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ztx', '0002_auto_20201119_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='costomer_id',
            new_name='costomer',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='costomer_id',
            new_name='costomer',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='product_id',
            new_name='product',
        ),
    ]
