# Generated by Django 3.1.4 on 2020-12-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ztx', '0004_income_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='价格'),
        ),
    ]
