# Generated by Django 3.1.4 on 2021-03-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ztx', '0005_trade_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costomer',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='income',
            name='type',
            field=models.CharField(choices=[('赫兹金卡', '赫兹金卡'), ('理疗卡', '理疗卡'), ('拔罐年卡', '拔罐年卡')], default='理疗卡', max_length=50, verbose_name='收入类型'),
        ),
    ]
