# Generated by Django 3.1.4 on 2021-03-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ztx', '0006_auto_20210309_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='amount',
            field=models.IntegerField(default=1, verbose_name='数量'),
        ),
    ]
